dependencies:
  - name: postgresql
    version: 6.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 9.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
