apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsqlookupd.fullname" . }}
  labels:
    {{- include "nsqlookupd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nsqlookupd.replicaCount }}
  revisionHistoryLimit: {{ .Values.nsqlookupd.revisionHistoryLimit }}
  podManagementPolicy: {{ .Values.nsqlookupd.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.nsqlookupd.updateStrategy }}
    {{- if (eq "Recreate" .Values.nsqlookupd.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.nsqlookupd.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.nsqlookupd.rollingUpdatePartition }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nsqlookupd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nsqlookupd.fullname" . }}-headless
  template:
    metadata:
      labels:
        {{- include "nsqlookupd.labels" . | nindent 8 }}
    spec:
    {{- with .Values.nsqlookupd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nsqlookupd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nsqlookupd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - command:
        - /nsqlookupd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "nsqlookupd.name" . }}
        ports:
        - name: tcp-port
          containerPort: {{ .Values.nsqlookupd.tcp_port | default "4160" }}
          protocol: TCP
        - name: http-port
          containerPort: {{ .Values.nsqlookupd.http_port | default "4161" }}
          protocol: TCP
      {{- with .Values.nsqlookupd.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.nsqlookupd.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
      {{- end }}
