{{- $nsqlookupdPortTcp  := .Values.nsqlookupd.tcp_port -}}
{{- $nsqName  := (include "nsq.name" .) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
    {{- include "nsqd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nsqd.replicaCount }}
  revisionHistoryLimit: {{ .Values.nsqd.revisionHistoryLimit }}
  podManagementPolicy: {{ .Values.nsqd.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.nsqd.updateStrategy }}
    {{- if (eq "Recreate" .Values.nsqd.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.nsqd.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.nsqd.rollingUpdatePartition }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nsqd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nsqd.fullname" . }}-headless
  template:
    metadata:
      labels:
        {{- include "nsqd.labels" . | nindent 8 }}
    spec:
    {{- with .Values.nsqd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nsqd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nsqd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: check-deps-ready
        image: dadarek/wait-for-dependencies
        command:
        - /bin/sh
        - /usr/local/bin/entrypoint.sh
        {{ range $i, $e := until (.Values.nsqlookupd.replicaCount | int) }}
        {{- printf "- %s-nsqlookupd-%d.%s-nsqlookupd-headless:%d" $nsqName $i $nsqName ($nsqlookupdPortTcp | int) }}
        {{ end }}
      containers:
      - command:
        - /bin/sh
        - -c
        - /nsqd
          -broadcast-address=$(POD_IP)
          -msg-timeout "{{ .Values.nsqd.msg_timeout }}"
          {{range $i, $e := until (.Values.nsqlookupd.replicaCount | int) }}
          {{- printf "--lookupd-tcp-address=%s-nsqlookupd-%d.%s-nsqlookupd-headless:%d" $nsqName $i $nsqName ($nsqlookupdPortTcp | int) }}
          {{ end }}
          --data-path=/nsqd-data
          --mem-queue-size={{ .Values.nsqd.mem_queue_size }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "nsqd.name" . }}
        ports:
        - name: tcp-port
          containerPort: {{ .Values.nsqd.tcp_port | default "4150" }}
          protocol: TCP
        - name: http-port
          containerPort: {{ .Values.nsqd.http_port | default "4151" }}
          protocol: TCP
        - name: https-port
          containerPort: {{ .Values.nsqd.https_port | default "4152" }}
          protocol: TCP
      {{- with .Values.nsqd.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.nsqd.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
      {{- end }}
        volumeMounts:
        - name: {{ include "nsqd.fullname" . }}-data
          mountPath: {{ include "nsqd.fullpath" . }}

      volumes:
      - name: {{ include "nsqd.fullname" . }}-data
      {{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "nsqd.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}

{{- if .Values.nsqd.persistentVolumeClaim.enabled }}
  volumeClaimTemplates:
{{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.enabled }}
  - metadata:
      name: {{ include "nsqd.fullname" . }}-data
      labels:
        app.kubernetes.io/name: {{ include "nsqd.name" . }}-data
        app.kubernetes.io/instance: {{ .Release.Name }}-data
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      accessModes:
    {{- range .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.accessModes }}
      - {{ . | quote }}
    {{- end }}
    {{- if (eq "-" .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storageClassName) }}
      storageClassName: ""
    {{- else }}
      storageClassName: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storageClassName | quote }}
    {{- end }}
    {{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.volumeMode }}
      volumeMode: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.volumeMode }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storage | quote }}
{{- end }}
{{- end }}
