apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ include "nsq.labels" . | indent 4 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nsq.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nsq.fullname" . }}-nsqd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nsq.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: NotIn
                    values:
                      - 'true'
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nsq
              topologyKey: kubernetes.io/hostname
      containers:
        - command:
            - /bin/sh
            - -c
            - /nsqd --lookupd-tcp-address=nsqlookup-0.nsqlookup:4160 --lookupd-tcp-address=nsqlookup-1.nsqlookup:4160
              --lookupd-tcp-address=nsqlookup-2.nsqlookup:4160 -broadcast-address=$POD_IP
              --data-path=/nsqd-data --mem-queue-size=200000 -msg-timeout "3m0s"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: nsqio/nsq:v0.3.8
          imagePullPolicy: IfNotPresent
          name: nsqd
          ports:
            - containerPort: 4150
              protocol: TCP
            - containerPort: 4151
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /nsqd-data
              name: nsqd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      subdomain: nsqd
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
        creationTimestamp: null
        name: nsqd
      spec:
        accessModes:
          - ReadWriteOnce
        dataSource: null
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
      status:
        phase: Pending
