apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
{{ include "nsqd.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  podManagementPolicy: {{ .Values.nsqd.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.nsqd.updateStrategy }}
    {{- if (eq "Recreate" .Values.nsqd.updateStrategy) }}
    rollingUpdate: null
    {{- else if .Values.nsqd.rollingUpdatePartition }}
    rollingUpdate:
      partition: {{ .Values.nsqd.rollingUpdatePartition }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nsqd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nsqd.fullname" . }}-headless
  template:
    metadata:
      labels:
{{ include "nsqd.labels" . | indent 8 }}

    spec:

    {{- if .Values.nsqd.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nsqd.nodeSelector | indent 8 }}
    {{- end }}

    {{- if .Values.nsqd.tolerations }}
      tolerations:
{{ toYaml .Values.nsqd.tolerations | indent 8 }}
    {{- end }}

    {{- if .Values.nsqd.affinity }}
      affinity:
{{ toYaml .Values.nsqd.affinity | indent 8 }}
    {{- end }}

    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
        - name: {{ . | quote }}
    {{- end }}
    {{- end }}

      containers:
      - command:
        - /bin/sh
        - -c
        - /nsqd --lookupd-tcp-address=nsqlookup-0.nsqlookup:4160 --lookupd-tcp-address=nsqlookup-1.nsqlookup:4160
          --lookupd-tcp-address=nsqlookup-2.nsqlookup:4160 -broadcast-address=$POD_IP
          --data-path=/nsqd-data --mem-queue-size={{ .Values.nsqd.mem_queue_size }} -msg-timeout "{{ .Values.nsqd.msg_timeout }}"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "nsqd.fullname" . }}
        ports:
        - name: tcp-port
          containerPort: {{ .Values.nsqd.tcp_port | default "4150" }}
          protocol: TCP
        - name: http-port
          containerPort: {{ .Values.nsqd.http_port | default "4151" }}
          protocol: TCP
        - name: https-port
          containerPort: {{ .Values.nsqd.https_port | default "4152" }}
          protocol: TCP
      {{- if .Values.nsqd.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.nsqd.tcp_port }}
          initialDelaySeconds: {{ .Values.nsqd.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.nsqd.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.nsqd.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.nsqd.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.nsqd.livenessProbe.successThreshold }}
      {{- end }}
      {{- if .Values.nsqd.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.nsqd.tcp_port }}
          initialDelaySeconds: {{ .Values.nsqd.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.nsqd.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.nsqd.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.nsqd.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.nsqd.readinessProbe.successThreshold }}
      {{- end }}
        volumeMounts:
        - name: {{ include "nsqd.fullname" . }}-data
          mountPath: {{ include "nsqd.fullpath" . }}
        securityContext:
          privileged: true
          runAsUser: 0

      volumes:
      - name: {{ include "nsqd.fullname" . }}-data
      {{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "nsqd.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}

{{/*      dnsPolicy: ClusterFirst*/}}
{{/*      restartPolicy: Always*/}}
{{/*      schedulerName: default-scheduler*/}}
{{/*      subdomain: nsqd*/}}
{{/*      terminationGracePeriodSeconds: 30*/}}

{{- if .Values.nsqd.persistentVolumeClaim.enabled }}
  volumeClaimTemplates:
{{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.enabled }}
  - metadata:
      name: {{ include "nsqd.fullname" . }}-data
      labels:
        app.kubernetes.io/name: {{ include "nsqd.name" . }}-data
        app.kubernetes.io/instance: {{ .Release.Name }}-data
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      accessModes:
    {{- range .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.accessModes }}
      - {{ . | quote }}
    {{- end }}
    {{- if (eq "-" .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storageClassName) }}
      storageClassName: ""
    {{- else }}
      storageClassName: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storageClassName | quote }}
    {{- end }}
    {{- if .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.volumeMode }}
      volumeMode: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.volumeMode }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.nsqd.persistentVolumeClaim.dataPersistentVolume.storage | quote }}
{{- end }}
{{- end }}
