apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqlookupd.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "nsqlookupd.name" . }}-headless
{{ include "nsq.labels.common" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.nsqlookupd.tcp_port }}
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: {{ .Values.nsqlookupd.http_port }}
    targetPort: http-port
    protocol: TCP
    name: http-port
  selector:
{{ include "nsqlookupd.labels" . | indent 4 }}
