apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqlookupd.fullname" . }}
  labels:
{{ include "nsqlookupd.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.nsqlookupd.tcp_port }}
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: {{ .Values.nsqlookupd.http_port }}
    targetPort: http-port
    protocol: TCP
    name: http-port
  selector:
{{ include "nsqlookupd.labels" . | indent 4 }}
