apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
{{ include "nsq.labels.common" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.nsqd.tcp_port }}
    targetPort: tcp-port
    protocol: TCP
    name: tcp-port
  - port: {{ .Values.nsqd.http_port }}
    targetPort: http-port
    protocol: TCP
    name: http-port
  - port: {{ .Values.nsqd.https_port }}
    targetPort: https-port
    protocol: TCP
    name: https-port
  selector:
    app: {{ include "nsqd.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
