apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clickhouse-bulk.fullname" . }}
  labels:
{{ include "clickhouse-bulk.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clickhouse-bulk.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clickhouse-bulk.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8124
              protocol: TCP

          ## Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated.
          ## More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
          livenessProbe:
            tcpSocket:
              port: 8124
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          ## Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated.
          ## More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
          readinessProbe:
            tcpSocket:
              port: 8124
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
