apiVersion: v1
appVersion: "1.2.0"
description: A realtime distributed messaging platform
home: https://nsq.io/
icon: https://nsq.io/static/img/nsq_favicon.png
name: nsq
version: 0.1.1
keywords:
  - nsq
  - message queue
  - messaging platform
  - distributed messaging
maintainers:
  - email: stephan@redlotus.com
    name: redlotuscorp
sources:
  - https://github.com/redlotus-corp/helm-charts
