{{- if .Values.tabix.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.tabix.service.name }}
  name: {{ .Values.tabix.service.name }}
{{- else }}
  name: {{ include "clickhouse.fullname" . }}-tabix
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}-tabix
    app.kubernetes.io/instance: {{ .Release.Name }}-tabix
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.tabix.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}-tabix
    app.kubernetes.io/instance: {{ .Release.Name }}-tabix
{{- end }}
